version: 2
jobs:
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npx semantic-release
workflows:
  version: 2
  ship_it:
    jobs:
      - release:
        filters:
          branches:
            only:
              - master
              - develop